def TAG = ""
def FULL_IMAGE_NAME = ""
pipeline {
    agent any
    environment {
        REPO_NAME = "ranjithasu"
        IMAGE_NAME = "java-mysql-app"
    }
    stages {
        stage('Build image') {
            steps {
                script {
                    echo "Building image"
                    def pom = readMavenPom file: 'pom.xml'
                    TAG = pom.version
                    FULL_IMAGE_NAME = REPO_NAME + "/" + IMAGE_NAME + ":" + TAG
                    sh "docker build -t ${FULL_IMAGE_NAME} ."
                }
            }
        }
        stage('Push Image') {
            environment {
                DOCKER_CREDENTIALS = credentials('DOCKERHUB_CREDS')
            }
            steps {
                script {
                    echo "Push image to private repository"
                    sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
                    sh "docker push $FULL_IMAGE_NAME"
                }
            }
        }
        stage('Deploy') {
            steps{
                script {
                    withCredentials([file(credentialsId: 'DEV_EKS_KUBECONFIG', variable: 'KUBECONFIG')]){
                        sh "kubectl apply -f kubernetes/mysql/secret.yaml"
                        sh "kubectl apply -f kubernetes/mysql/config.yaml"
                        sh "kubectl apply -f kubernetes/mysql/deployment.yaml"
                        sh "kubectl apply -f kubernetes/mysql/service.yaml"
                        sh "envsubst < kubernetes/app/deployment.yaml | kubectl apply -f -"
                        sh "envsubst < kubernetes/app/service.yaml | kubectl apply -f -"
                    }
                }
            }
        }
    }
}